[package]
name = "server"
version = "0.0.0"
authors = ["LightningPeach <contact@lightningpeach.com>"]

[[bin]]
name = "server"

[dependencies]
grpc = "0.6.*"
tls-api = "0.1.*"
tls-api-native-tls = "0.1.2"
httpbis = "0.7.*"
native-tls = "0.2"
ctrlc = "3.1"
secp256k1 = "0.12"
hex = "0.3"

futures = "0.1"

bitcoin = "0.18"

implementation = { path = "../implementation" }
connection = { path = "../../connection" }
