[workspace]
members = ["../lpd", "bincode", "wire", "brontide", "shachain", "hdkeychain", "channel"]

[package]
name = "lpd"
version = "0.0.0"
description = "The implementation of a Lightning Network node"
license = "Apache-2.0"
authors = ["LightningPeach <contact@lightningpeach.com>"]

[lib]
name = "lpd"

[[example]]
name = "wasm-basic"
crate-type = ["cdylib"]

[[example]]
name = "wasm-runner"

[[example]]
name = "run-lnd"


[dependencies]
wire = { path = "wire" }
brontide = { path = "brontide" }
shachain = { path = "shachain" }
hdkeychain = { path = "hdkeychain" }
channel = { path = "channel" }

rand = "0.5.4"
secp256k1 = "0.9.2"
hex = "0.3.2"
serde = "1"

bitcoin = "0.13.2"
rust-crypto = "0.2.36"

[dev-dependencies]
serde_derive = "1.0.70"