[package]
name = "channel"
version = "0.0.0"
authors = ["Mykola Sakhno <mykola.sakhno@bitfury.com>"]
description = "The implementation of a Lightning channel"
license = "Apache-2.0"

[dependencies]
rand = "0.5.4"
secp256k1 = "0.9.2"
hex = "0.3.2"
bitcoin = "0.13.2"
rust-crypto = "0.2.36"